from __future__ import annotations


class AioLd2410Error(Exception):
    """Base error for exceptions generated by this library."""


class CommandError(AioLd2410Error):
    """An error raised after a command was sent."""


class CommandStatusError(CommandError):
    """An error raised after a failure status was received."""


class ModuleRestartedError(BaseException):
    """Raised when the module is restarting.

    Do not catch this exception, it is used by the configuration context.
    """
