name: "Check typing with MyPy"
on:
  push:
    paths:
      - '*.py'
  pull_request:
    paths:
      - '*.py'
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.12"

jobs:
  mypy:
    name: "Run mypy"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: "Install linting dependendies"
        run: make install-package install-linting
      - name: "Run mypy"
        run: mypy
        continue-on-error: true
