name: Build and publish python packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:


jobs:
  build:
    name: Build package distribution
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: make install-package

      - name: Build both wheel and source package
        run: make build

      - name: Check wheel package installation
        run: pip install dist/aio_ld2410-*.whl --force-reinstall

      - name: Upload distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist

  publish-pypi:
    name: Publish to PyPI
    needs:
      - build
    runs-on: ubuntu-latest

    # Only publish to PyPI on tag pushes.
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    environment:
      name: pypi
      url: 'https://pypi.org/p/aio-ld2410'

    permissions:
      # For PyPI's trusted publishing.
      id-token: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist/

      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          packages-dir: dist
          verbose: true

  github-release:
    name: Sign packages and upload them to GitHub Release
    needs:
      - publish-pypi
    runs-on: ubuntu-latest

    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
      id-token: write  # IMPORTANT: mandatory for sigstore

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist/

      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v2.1.1
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >
          gh release create '${{ github.ref_name }}'
          --repo '${{ github.repository }}'
          --title '${{ github.ref_name }}'

      - name: Upload artifact and signatures to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        # Upload to GitHub Release using the `gh` CLI.
        # `dist/` contains the built packages, and the sigstore-produced signatures and certificates.
        run: |
          gh release upload '${{ github.ref_name }}' dist/** --repo '${{ github.repository }}'
