name: Check linting with ruff
on:
  push:
    paths:
      - '.github/workflows/ruff.yml'
      - 'pyproject.toml'
      - '**.py'
  pull_request:
    paths:
      - '.github/workflows/ruff.yml'
      - 'pyproject.toml'
      - '**.py'
  workflow_dispatch:

jobs:
  ruff:
    name: Run ruff
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version:  ${{ matrix.python-version }}

      - name: Install linting dependencies
        run: make install-linting

      - name: Run ruff with linting checks
        run: ruff check --output-format=github

      - name: Run ruff with format checks
        run: ruff format --check --diff
        if: success() || failure()
